# Generated by Django 4.2.4 on 2023-08-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=250)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('taxa_extra', models.IntegerField(default=0)),
                ('custo_total_com_extra', models.DecimalField(decimal_places=2, default=0, max_digits=1000, null=True)),
                ('porcoes', models.IntegerField(default=0)),
                ('custo_por_porcao', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('custo_por_porcao_com_extra', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=250)),
                ('tipo_medida', models.CharField(choices=[('gramas', 'Gramas'), ('mililitros', 'Mililitros'), ('unidade', 'Unidade')], max_length=50)),
                ('valor_gasto', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('qnt_comprada', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('qnt_utilizada', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='app_cad_receitas.receitas')),
            ],
        ),
    ]
